feat: rowset and rowrange api
Unoperate/tensorflow_io pull request #3
Opened 2021-10-28 10:52 UTC by kboroszko

This pr adds python api and c++ implementation for handling row_sets and row_ranges

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unoperate/tensorflow_io/3)

2021-11-02 14:36 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 11 files reviewed, 19 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 455 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn6p85Z18ksB5fxOcKX:-MnVoTFYAt6ydBXqboTa:bn3xr5y) ([raw file](https://github.com/unoperate/tensorflow_io/blob/7525637d11095fa6b17f003eb7a371975d72ea81/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L455)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

`LOG(FATAL)` maybe? I think this will crash the program but output the log line first.
</blockquote></details>

How do you know that?
Also, I found a namespace tensorflow::errors with some error statuses defined. I followed convention from other kernels. WDYT?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 460 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn6pcHLBM-ytRAheOYZ:-MnVovumBK5lrR26VqDC:b-be23ba) ([raw file](https://github.com/unoperate/tensorflow_io/blob/7525637d11095fa6b17f003eb7a371975d72ea81/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L460)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Make those const, please.
</blockquote></details>

I can't. I have to set them by calling `context->GetAttr(...)` which takes a pointer as an argument, and `const` members have to be initialized before the body of the constructor, no? 

I could try to work around it and create a method that would create a pointer to a value, pass it to `GetAttr()` and then return the value, but this seems like fighting the framework which I don't think we should do. 
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 123 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9leGI6FN8xSmeOOy4:-MnVLCC7EjVYC08Ddb8T:b-1qo18k) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L123)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This is unrelated and, more importantly, that's not how we should do error handling. Please make another PR with proper error handling with an integration test. I'm assuming TF can somehow fail an operation.
</blockquote></details>

Will do, changing this to LOG(ERROR) for now.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 311 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9nYa36oUbyeJZHpZJ:-MnVMdS8C7iOMv9PWMdA:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L311)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It's a member function of a `RowSet`. Simple `Print()` should suffice. BTW, it's more of `ToString()` - it doesn't print anything.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 317 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9lyb72ZzwjQ8YtO_t:-MnVOVZ036SqlEUBYJce:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L317)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please avoid naming members by their type. `AppendRow` seems more appropriate.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 325 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9odpR0bkMClfEMKj3:-MnVOW-W7lHk0pYszm8A:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L325)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Since you've added `PrintRowSet`, why not use it here?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 327 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9mrMn2SuUhehSimly:-MnVOcgf4D8C3gt1DX8Y:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L327)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This should be `private`, no?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 332 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9mPjo0AgTZl8IJj2z:-MnVYekTEdqA0gSucWNU:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L332)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

You're using a `std::move` on a cref. Please make this ctor take the argument by value.

As a general guideline, constructors which store an argument should take them by value and `std::move` them.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 339 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9nFQuC-zU3yg7yt9a:-MnVYfsR9pmMNc81pvJb:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L339)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

It's a member function of a `RowRange`. Simple `Print()` should suffice. BTW, it's more of `ToString()` - it doesn't print anything.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 347 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9n8pjAHEpvSmyMlAy:-MnVYhXu2OUNQbfPssTx:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L347)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Since you've added `PrintRowRange`, why not use it here?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 349 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9mn__5_a7gMnLb1bw:-MnVYiGZ2rVHG7oAfhBb:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L349)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This should be `private`, no?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 353 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9pCvvBJXgst_Com3Y:-MnVlOYzBzmlvPZnkcGv:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L353)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think the name of this class stopped making sense. Could you please change it to something more appropriate?
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 358 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9pLeqD67WLs5abBp3:-MnVm3B237-lzMbWiIdR:b-896fix) ([raw file](https://github.com/unoperate/te [...]

2021-11-02 14:38 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 11 files reviewed, 19 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tests/test_bigtable/bigtable_emulator.py, line 1 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9sSIm9iXXGQRSGOAM:-MnW4GU73wg1CPmUoqtC:b-9zrhbb) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tests/test_bigtable/bigtable_emulator.py#L1)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

right, probably we do...
</blockquote></details>

I think we should leave it for now and worry about that at the end. Definitely out of scope for this PR though.


<!-- Sent from Reviewable.io -->

2021-11-02 15:41 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 15 files reviewed, 19 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 302 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9qrHg7Kcjuk0OUCeU:-MnWJ-IfEIB_DNg7gNLr:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L302)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think this file is growing too long. Could you please move those to separate files? E.g. `row_range.cc` and `row_set.cc`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-03 18:35 UTC, dopiera commented
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 455 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn6p85Z18ksB5fxOcKX:-Mnb2uBz3BJJJ-3M5v7L:bjszelz) ([raw file](https://github.com/unoperate/tensorflow_io/blob/7525637d11095fa6b17f003eb7a371975d72ea81/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L455)):*
To quote Monty Python:
> You have to know these things when you're king, you know.

It uses `LogMessageFatal`, which is documented this way:
> LogMessageFatal ensures the process will exit in failure after logging this message.


Let's move the discussion on the particular error to the new file.


<!-- Sent from Reviewable.io -->

2021-11-03 19:36 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 15 files reviewed, 19 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 460 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn6pcHLBM-ytRAheOYZ:-MnatGZKA-gCYx4Ttj8u:b7sff3y) ([raw file](https://github.com/unoperate/tensorflow_io/blob/7525637d11095fa6b17f003eb7a371975d72ea81/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L460)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

I can't. I have to set them by calling `context->GetAttr(...)` which takes a pointer as an argument, and `const` members have to be initialized before the body of the constructor, no? 

I could try to work around it and create a method that would create a pointer to a value, pass it to `GetAttr()` and then return the value, but this seems like fighting the framework which I don't think we should do. 
</blockquote></details>

You're right. Not the prettiest API...
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 123 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9leGI6FN8xSmeOOy4:-MnatQeB9PrqOwKR8gWu:bwgkmj6) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L123)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Will do, changing this to LOG(ERROR) for now.
</blockquote></details>

Seems that you did manage to find a proper way to fail it, but as a general rule, please include more error details in the error you return.

BTW, wouldn't simply `return row.status()` work?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 388 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9ozh54xVxDRFwCKTz:-MnaxjsRE4un3meHOggn:b5i7mir) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L388)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Generally it can fail, so I added a check for that.
mgr->Create() needs a pointer to the resource so I have to create it anyways. At best I can return a reference, not a value.
</blockquote></details>

The only place it can fail is a bug in the implementation of the `BigtableRowRangeOp`. I'm of the tribe which prefers assertions in such places (i.e. where the failure is due to a bug in the code you control, rather than external circumstances like network) because it's oftentimes a symptom of your application misbehaving in even nastier ways.

Irrespective of whether you choose to belong to the assert or fail-gracefully tribe I think this API can be made much more readable by returning a `StatusOr<BigtableRowRangeResource*>`.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 29 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb5BiA6EDqDdWkM5WA:-Mnb5BiA6EDqDdWkM5WB:b-mqgm2f) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L29)):*
> ```objc
> #include "tensorflow/core/framework/resource_op_kernel.h"
> 
> using ::tensorflow::DT_STRING;
> ```

This is legal in a `.cc` file, but not in a header file because it will pollute the global namespace for any file which includes this file.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 34 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb5XiFBDU8c3k8mv23:-Mnb5XiFBDU8c3k8mv24:b-epwi4t) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L34)):*
> ```
> cbt
> ```
Same here - please don't pollute the global namespace, especially that this is not used.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 36 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb6WdT7B3ktNkf08gm:-Mnb6WdT7B3ktNkf08gn:b9ebo7c) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L36)):*
> ```objc
> 
> namespace tensorflow {
> namespace {
> ```

A class in an anonymous namespace in a header is playing with fire. This will yield a separate class in every compilation unit, which can lead to some weird bugs. Please drop that anonymous namespace.

Also, other files use the `tensorflow::data` namespace - it seems that `tensorflow::io` is the new thing, which we should use instead.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 39 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb980I-CI1jLDNRD93:-Mnb980I-CI1jLDNRD94:b-smbayf) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L39)):*
> ```
> OpKernelCreatingResource
> ```
It seems that people follow the `SomeNounsOp` for those names, so I think so should we.

How about `AbstractBigtableResourceOp`?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 44 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb9XiR6gVxAVXWVTtb:-Mnb9XiR6gVxAVXWVTtc:bdhy1ch) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L44)):*
> ```
> TF_LOCKS_EXCLUDED
> ```
I think these concurrency annotations are stale, please remove them.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 61 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb9iLD1ayXG-sq0t5q:-Mnb9iLD1ayXG-sq0t5r:bneqq45) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L61)):*
> ```
> Status CreateResource
> ```
As suggested elsewhere, I think `virtual StatusOr<T> CreateResource()` would be a better API.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 31 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbCdFP8JCXNkGvDRyD:-MnbCdFP8JCXNkGvDRyE:bgnqoeh) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L31)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> using ::tensorflow::DT_STRING;
> using ::tensorflow::PartialTensorShape;
> using ::tensorflow::Status;
> 
> namespace cbt = ::google::cloud::bigtable;
> ```
</details>


As I mentioned elsewhere - please don't do this in header files.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 38 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbCNIq6zAJmr_m8-jv:-MnbCNIq6zAJmr_m8-jw:b-8dee86) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L38)):*
> ```objc
> namespace tensorflow {
> namespace data {
> namespace {
> ```

As I mentioned elsewhere - please use `tensorflow::io` and drop the anonymous namespace from the header files.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 55 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbDVKx3dOUNCVJhQ4C:-MnbDVKx3dOUNCVJhQ4D:b-nmyy69) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L55)):*
> ```
> RowRange
> ```
By convention, accessors are named the same as the me [...]

2021-11-04 06:28 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 17 files reviewed, 19 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 455 at r2](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn6p85Z18ksB5fxOcKX:-MndXV4B7GF2hgwE717B:bc52tdo) ([raw file](https://github.com/unoperate/tensorflow_io/blob/7525637d11095fa6b17f003eb7a371975d72ea81/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L455)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

To quote Monty Python:
> You have to know these things when you're king, you know.

It uses `LogMessageFatal`, which is documented this way:
> LogMessageFatal ensures the process will exit in failure after logging this message.


Let's move the discussion on the particular error to the new file.
</blockquote></details>

:laughing: 
___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 123 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9leGI6FN8xSmeOOy4:-MndXcWp-G6SESdsFlwM:b-6nmkut) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L123)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Seems that you did manage to find a proper way to fail it, but as a general rule, please include more error details in the error you return.

BTW, wouldn't simply `return row.status()` work?
</blockquote></details>

tensorflow::Status and google::cloud::Status are two different things I'm affraid.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 29 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb5BiA6EDqDdWkM5WA:-MndYQFE8mOGtJhIMlC_:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L29)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This is legal in a `.cc` file, but not in a header file because it will pollute the global namespace for any file which includes this file.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 34 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb5XiFBDU8c3k8mv23:-MndYSuFE0cfRb8_DRJO:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L34)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> cbt
> ```
Same here - please don't pollute the global namespace, especially that this is not used.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 36 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb6WdT7B3ktNkf08gm:-MndYregDXHBCWJyhrOd:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L36)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

A class in an anonymous namespace in a header is playing with fire. This will yield a separate class in every compilation unit, which can lead to some weird bugs. Please drop that anonymous namespace.

Also, other files use the `tensorflow::data` namespace - it seems that `tensorflow::io` is the new thing, which we should use instead.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 39 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb980I-CI1jLDNRD93:-MndZKl72I8AlqNxL0o3:bvnepkg) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L39)):*
> AbstractBigtableResourceOp
I love it.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 31 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbCdFP8JCXNkGvDRyD:-MndZbF74BlVKc-F-T4J:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L31)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> using ::tensorflow::DT_STRING;
> using ::tensorflow::PartialTensorShape;
> using ::tensorflow::Status;
> 
> namespace cbt = ::google::cloud::bigtable;
> ```

As I mentioned elsewhere - please don't do this in header files.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 38 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbCNIq6zAJmr_m8-jv:-MndZbxI5ejXNdmfzyhy:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L38)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

As I mentioned elsewhere - please use `tensorflow::io` and drop the anonymous namespace from the header files.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 55 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbDVKx3dOUNCVJhQ4C:-Mnd_D9S2-VM3-JGPgMu:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L55)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> RowRange
> ```
By convention, accessors are named the same as the member but without the underscore, i.e. `row_range()` in this case.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 65 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbA_wEDZ4ugfaINiMn:-Mndc_eY0LTKqlDDRhmp:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L65)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> BigtableEmptyRowRangeOp
> ```
I think this and all other specific operations should go to the `*.cc` file, no? There's no point in having them declared (and registered) in every compilation unit, I think.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-04 12:22 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 17 files reviewed, 19 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 388 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9ozh54xVxDRFwCKTz:-MnetedX1j_yCB_iJlwF:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L388)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

The only place it can fail is a bug in the implementation of the `BigtableRowRangeOp`. I'm of the tribe which prefers assertions in such places (i.e. where the failure is due to a bug in the code you control, rather than external circumstances like network) because it's oftentimes a symptom of your application misbehaving in even nastier ways.

Irrespective of whether you choose to belong to the assert or fail-gracefully tribe I think this API can be made much more readable by returning a `StatusOr<BigtableRowRangeResource*>`.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 44 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb9XiR6gVxAVXWVTtb:-MneE0MQ9G_KNbSQqc0y:b-7rl0jd) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L44)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> TF_LOCKS_EXCLUDED
> ```
I think these concurrency annotations are stale, please remove them.
</blockquote></details>

done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 61 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb9iLD1ayXG-sq0t5q:-Mnetg2OD0QpM3w1DJtI:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L61)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> Status CreateResource
> ```
As suggested elsewhere, I think `virtual StatusOr<T> CreateResource()` would be a better API.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 75 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbB6tB83jfD54M09zT:-MndiIIwEwI-cJN6H7HQ:b-si129x) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L75)):*
> TF_EXCLUSIVE_LOCKS_REQUIRED(mu_)
I tried, and when I do that it compiles alright, but when I run it I get this strange error:
```NotImplementedError: unable to open file: /home/kajetan/git/tensorflow_io/tensorflow_io/python/ops/__init__.py, from paths: ['/home/kajetan/git/tensorflow_io/tensorflow_io/python/ops/libtensorflow_io.so', 'bazel-bin/tensorflow_io/python/ops/libtensorflow_io.so']
E       caused by: ['/home/kajetan/git/tensorflow_io/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory', 'bazel-bin/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZN10tensorflow2io26AbstractBigtableResourceOpINS0_22BigtableRowsetResourceEE14CreateResourceEPPS2_'```

That symbol demangled is:
`tensorflow::io::AbstractBigtableResourceOp<tensorflow::io::BigtableRowsetResource>::CreateResource(tensorflow::io::BigtableRowsetResource**)`

When I don't use the flag, python seems to  unable to find the right symbol for that method. It's wierd, any idea what that's about?
```

___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 85 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbBTsN3zgbIPdnn5vB:-MndivNIEsYlCzZt6nW2:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L85)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> REGISTER_KERNEL_BUILDER(Name("BigtableEmptyRowRange").Device(DEVICE_CPU),
>                         BigtableEmptyRowRangeOp);
> ```
I don't think the header is where we're supposed to register the operations. This macro will be called in every compilation unit including this file. I don't know what it does internally, but this doesn't sound right, especially that it's called in `*.cc` files everywhere else in the code.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 136 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbDrsJ810qpaEgpgfZ:-Mndj0nYCCnf8SE3fCw3:b-v5z2i5) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L136)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Whenever you return an error, please think of the poor user getting it and of your future self debugging this. It would be beneficial to future you to know what the values of `left_open` and `right_open` were. The user will have no clue what just happened - please let them know they've just stumbled upon a bug and they should report it.

Here's an example how to do it:
https://github.com/googleapis/google-cloud-cpp/blob/5403c4889924f84ecfc020b62e8c189ea3b441e6/google/cloud/storage/internal/retry_resumable_upload_session.cc#L77
</blockquote></details>

hahah, Oh that poor user! Sure, I changed it. I wasn't very descriptive of that error message because this error here exists just because the compiler is too stupid to understand that this branch is truly impossible to reach. Prior 4 if statements provide for all possible boolean values of `left_open` and `right_open`. I guess if the code above ever changes then this error would make sense.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.h, line 32 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbHWu-BW7iUMUIOlkK:-Mndrdrj5eNPfS5bpu2I:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_set.h#L32)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> using ::tensorflow::DT_STRING;
> using ::tensorflow::PartialTensorShape;
> using ::tensorflow::Status;
> 
> namespace cbt = ::google::cloud::bigtable;
> 
> namespace tensorflow {
> namespace data {
> namespace {
> ```
Please apply the comments about the namespaces from other files here too.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.h, line 45 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnanLyi9euNZH04uzCU:-Mndt1Vb5rGucnXAuROb:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_set.h#L45)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Why not put it in the initializer list?

BTW, you're taking the argument by a cref, so that `std::move` doesn't change anything - please make the ctor take the argument by value.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_set.h, line 105 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb1cKY5YTfQS2Dmngb:-MndtNUv7YQ3giA2K4U-:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_set.h#L105)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please remove this comment
</blockquote></details>

Done. [...]

2021-11-04 18:06 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 17 files reviewed, 11 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 123 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9leGI6FN8xSmeOOy4:-Mng0g640gj4eYg2c1rb:b-bxjhk5) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L123)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

tensorflow::Status and google::cloud::Status are two different things I'm affraid.
</blockquote></details>

Right, but we still want to return meaningful errors. Currently, when the connection breaks, the user gets an "out of range" exception with no details about the reason - it's very misleading.

Bigquery implemented `GrpcStatusToTfStatus`. It seems that we should move it out of Bigquery (in a separate PR) and use it. Alternatively, we could perhaps create a dependency to bigquery?
___
*[tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h, line 61 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mnb9iLD1ayXG-sq0t5q:-Mng30Hd8_YSqi7NIvEu:b-kcvztj) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_resource_kernel.h#L61)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please drop the annotation - we don't even have that mutex.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 75 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbB6tB83jfD54M09zT:-Mng3KUbBCBHEyjwbbk0:b-xuy70n) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L75)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

> TF_EXCLUSIVE_LOCKS_REQUIRED(mu_)
I tried, and when I do that it compiles alright, but when I run it I get this strange error:
```NotImplementedError: unable to open file: /home/kajetan/git/tensorflow_io/tensorflow_io/python/ops/__init__.py, from paths: ['/home/kajetan/git/tensorflow_io/tensorflow_io/python/ops/libtensorflow_io.so', 'bazel-bin/tensorflow_io/python/ops/libtensorflow_io.so']
E       caused by: ['/home/kajetan/git/tensorflow_io/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory', 'bazel-bin/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZN10tensorflow2io26AbstractBigtableResourceOpINS0_22BigtableRowsetResourceEE14CreateResourceEPPS2_'```

That symbol demangled is:
`tensorflow::io::AbstractBigtableResourceOp<tensorflow::io::BigtableRowsetResource>::CreateResource(tensorflow::io::BigtableRowsetResource**)`

When I don't use the flag, python seems to  unable to find the right symbol for that method. It's wierd, any idea what that's about?
```

</blockquote></details>

I tried reproducing it, but I'm failing. Have you tried removing bazel's cache and rebuilding everything? It built (and loaded) just fine for me without those annotations.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 136 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbDrsJ810qpaEgpgfZ:-Mng3iBv3D6-aTLHzxjv:b-q4goj) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L136)):*
<details><summary><i>Previously, kboroszko (Kajetan Boroszko) wrote…</i></summary><blockquote>

hahah, Oh that poor user! Sure, I changed it. I wasn't very descriptive of that error message because this error here exists just because the compiler is too stupid to understand that this branch is truly impossible to reach. Prior 4 if statements provide for all possible boolean values of `left_open` and `right_open`. I guess if the code above ever changes then this error would make sense.
</blockquote></details>

Which is why I belong to the assert-rather-than-fail-gracefully-tribe in such cases :). That would allow you to get rid of the `StatusOr` from the function signature altogether. Anyway, please also tell the user that this is a bug on our end and they should file a report.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 40 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng6cJG7ile0g3i7eBQ:-Mng6cJG7ile0g3i7eBR:b59ex4o) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/core/ops/bigtable_ops.cc#L40)):*
> ```
> rowset
> ```
Please homogenize the naming. In some places you're calling it `rowset` and in others `row_set`. The same applies to `rowrange`.

Actually, the same applies to outputs, too.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 54 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng6nkFDG5KczXoL2Px:-Mng6nkFDG5KczXoL2Py:b-9hzoh7) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/core/ops/bigtable_ops.cc#L54)):*
> ```
> _str
> ```
Please drop the `_str` suffix - we've already indicated it's a string.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 71 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng5JLIEC1gJzTQshkG:-Mng5JLJ-cuuXlYsC4wj:bs8snn9) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/core/ops/bigtable_ops.cc#L71)):*
> ```cpp
> 
> REGISTER_OP("BigtablePrintRowRange")
>     .Input("resource: resource")
> ```

The name of the input is very misleading - it indicates the (opaque) type rather than what it is.

Please change it to something more meaningful, e.g. `row_range`. Please also do the same with the other operators.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 85 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng5k-T0MhRbAWOxpzZ:-Mng5k-T0MhRbAWOxpz_:bq690ie) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/core/ops/bigtable_ops.cc#L85)):*
> ```
> row_set_resource
> ```
I don't think the `_resource` suffix carries carries any extra information - I think we should drop it. The same for the other operators.
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 34 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng72lH9ueJ-GbgBvsM:-Mng72lI0_znML_R07GU:bx6afru) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L34)):*
> ```Python
>     def read_rows(self, columns: List[str]):
>         return _BigtableDataset(self._client_resource, self._table_id, columns)
> ```

This change seems accidental.


<!-- Sent from Reviewable.io -->

2021-11-05 13:56 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 17 files reviewed, 11 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 123 at r3](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mn9leGI6FN8xSmeOOy4:-MnkNXEH1E1PBdzRUQk2:b-gg45h5) ([raw file](https://github.com/unoperate/tensorflow_io/blob/8a9a02ce5fefca9488f43400e8eed07d016cc179/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L123)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Right, but we still want to return meaningful errors. Currently, when the connection breaks, the user gets an "out of range" exception with no details about the reason - it's very misleading.

Bigquery implemented `GrpcStatusToTfStatus`. It seems that we should move it out of Bigquery (in a separate PR) and use it. Alternatively, we could perhaps create a dependency to bigquery?
</blockquote></details>

The method you quoted takes `grpc::Status`, so I had to write one for `google::cloud::Status`
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 75 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbB6tB83jfD54M09zT:-Mnk7jD19AMJiK8MheDp:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L75)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I tried reproducing it, but I'm failing. Have you tried removing bazel's cache and rebuilding everything? It built (and loaded) just fine for me without those annotations.
</blockquote></details>

Done.
___
*[tensorflow_io/core/kernels/bigtable/bigtable_row_range.h, line 136 at r5](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnbDrsJ810qpaEgpgfZ:-MnkBDyIBoUGh6dH4mhr:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/6b5d09274242f298c810345456122d5c2f833ca0/tensorflow_io/core/kernels/bigtable/bigtable_row_range.h#L136)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Which is why I belong to the assert-rather-than-fail-gracefully-tribe in such cases :). That would allow you to get rid of the `StatusOr` from the function signature altogether. Anyway, please also tell the user that this is a bug on our end and they should file a report.
</blockquote></details>

Done.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 40 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng6cJG7ile0g3i7eBQ:-MnkF5e0BtPWWDac8IyZ:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/core/ops/bigtable_ops.cc#L40)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> rowset
> ```
Please homogenize the naming. In some places you're calling it `rowset` and in others `row_set`. The same applies to `rowrange`.

Actually, the same applies to outputs, too.
</blockquote></details>

Done.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 54 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng6nkFDG5KczXoL2Px:-MnkFbYgC0lL9FYr2ufI:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/core/ops/bigtable_ops.cc#L54)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> _str
> ```
Please drop the `_str` suffix - we've already indicated it's a string.
</blockquote></details>

Done.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 71 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng5JLIEC1gJzTQshkG:-MnkI2cW6mD3fUogyfDx:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/core/ops/bigtable_ops.cc#L71)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

The name of the input is very misleading - it indicates the (opaque) type rather than what it is.

Please change it to something more meaningful, e.g. `row_range`. Please also do the same with the other operators.
</blockquote></details>

Done.
___
*[tensorflow_io/core/ops/bigtable_ops.cc, line 85 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng5k-T0MhRbAWOxpzZ:-MnkI4TeAkjRc_nIj7oE:b-896fix) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/core/ops/bigtable_ops.cc#L85)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> row_set_resource
> ```
I don't think the `_resource` suffix carries carries any extra information - I think we should drop it. The same for the other operators.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-05 15:44 UTC, dopiera requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @dopiera and @kboroszko)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 71 at r10](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnkjMThAh5kyyy7k9qU:-MnkjMThAh5kyyy7k9qV:bbnezjz) ([raw file](https://github.com/unoperate/tensorflow_io/blob/9aa84107727c75b778d1a06409622152c85e9d42/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L71)):*
> ```
> Grpc
> ```
It's not gRPC.


<!-- Sent from Reviewable.io -->

2021-11-05 15:48 UTC, kboroszko reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc, line 71 at r10](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-MnkjMThAh5kyyy7k9qU:-MnkmD5NBR1NqJQcu8jT:b64cy7p) ([raw file](https://github.com/unoperate/tensorflow_io/blob/9aa84107727c75b778d1a06409622152c85e9d42/tensorflow_io/core/kernels/bigtable/bigtable_dataset_kernel.cc#L71)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> Grpc
> ```
It's not gRPC.
</blockquote></details>

Whoops...
___
*[tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py, line 34 at r8](https://reviewable.io/reviews/unoperate/tensorflow_io/3#-Mng72lH9ueJ-GbgBvsM:-MnklUet9FYnrnRtf1Vi:bgldyzm) ([raw file](https://github.com/unoperate/tensorflow_io/blob/1a1048ce181e70cc600d57c49018d75203e386f5/tensorflow_io/python/ops/bigtable/bigtable_dataset_ops.py#L34)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This change seems accidental.
</blockquote></details>

It was. I run the linter on all .py files to unify the spacing. It should be good now.


<!-- Sent from Reviewable.io -->

2021-11-05 15:51 UTC, dopiera approved these changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/tensorflow_io/3)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @dopiera)



<!-- Sent from Reviewable.io -->

2021-11-05 15:55 UTC, merged